// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.CentralModels;

public partial class AspNetUser
{
    public string Id { get; set; }

    public string Ciudad { get; set; }

    public int? CodigoPais { get; set; }

    public string Direccion { get; set; }

    public bool? Estado { get; set; }

    public DateTime? FechaNacimiento { get; set; }

    public string Nombre { get; set; }

    public string Pais { get; set; }

    public string Telefono { get; set; }

    public string Url { get; set; }

    public bool Deshabilitado { get; set; }

    public string ActualizadoPor { get; set; }

    public DateTime? UltimaActualizacion { get; set; }

    public string Email { get; set; }
}