// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.CentralModels;

public partial class ConfiguracionSistema
{
    public int ConfiguracionSistemaId { get; set; }

    public int FacturaSerie { get; set; }

    public int FacturaNumero { get; set; }

    public int BoletaSerie { get; set; }

    public int BoletaNumero { get; set; }

    public int HistoriaClinicaNumero { get; set; }

    public int TriageNumero { get; set; }

    public string EmailAdministrador { get; set; }

    public float Igv { get; set; }

    public int FacturaUltimoNumero { get; set; }

    public int BoletaUltimoNumero { get; set; }

    public float HistoriaClinicaUltimoNumero { get; set; }

    public int? BoletaSerieAntares { get; set; }

    public int? FacturaSerieAntares { get; set; }

    public int? FacturaNumeroAntares { get; set; }

    public int? BoletaNumeroAntares { get; set; }

    public int? FacturaUltimoNumeroAntares { get; set; }

    public int? BoletaUltimoNumeroAntares { get; set; }

    public string DefaultPrinter { get; set; }

    public string DefaultPrinterAntares { get; set; }

    public int? NotaCreditoSerie { get; set; }

    public int? NotaCreditoSerieAntares { get; set; }

    public int? FacturaSerieWiese { get; set; }

    public int? BoletaSerieWiese { get; set; }

    public int? NotaCreditoSerieWiese { get; set; }

    public int? BoletaUltimoNumeroWiese { get; set; }

    public int? FacturaUltimoNumeroWiese { get; set; }

    public int? NotaCreditoUltimoNumeroWiese { get; set; }

    public int? NotaCreditoUltimoNumeroAntares { get; set; }

    public int? NotaCreditoUltimoNumero { get; set; }

    public int? NotaCreditoSerie2 { get; set; }

    public int? NotaCreditoUltimoNumero2 { get; set; }

    public int FacturaSerieSede2 { get; set; }

    public int FacturaNumeroIniSede2 { get; set; }

    public float IgvSede2 { get; set; }

    public int FacturaUltimoNumeroSede2 { get; set; }

    public int BoletaSerieSede2 { get; set; }

    public int BoletaNumeroIniSede2 { get; set; }

    public int BoletaUltimoNumeroSede2 { get; set; }

    public int NcFacturaSerieSede2 { get; set; }

    public int NcFacturaUltimoNumeroSede2 { get; set; }

    public int NcBoletaSerieSede2 { get; set; }

    public int NcBoletaUltimoNumeroSede2 { get; set; }
}