// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.CentralModels;

public partial class Departamento
{
    public int CodigoDepartamento { get; set; }

    public short CodigoPais { get; set; }

    public string Nombre { get; set; }

    public virtual Pais CodigoPaisNavigation { get; set; }

    public virtual ICollection<Provincia> Provincia { get; set; } = new List<Provincia>();

}