// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.CentralModels;

public partial class Distrito
{
    public int CodigoDistrito { get; set; }

    public int CodigoProvincia { get; set; }

    public string Nombre { get; set; }

    public string CodigoPostal { get; set; }
    public virtual Provincia CodigoProvinciaNavigation { get; set; }
}