// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.CentralModels;

public partial class EmailQueue
{
    public int EmailQueueId { get; set; }

    public int SystemId { get; set; }

    public string EmailFrom { get; set; }

    public string EmailFromDisplay { get; set; }

    public string EmailTo { get; set; }

    public string EmailCc { get; set; }

    public string EmailBcc { get; set; }

    public string EmailSubject { get; set; }

    public string EmailFiles { get; set; }

    public string EmailBody { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string SmtpServer { get; set; }

    public string SmtpUser { get; set; }

    public string SmtpPwd { get; set; }

    public string SmtpPort { get; set; }

    public bool SmtpSsl { get; set; }

    public string QueueStatus { get; set; }

    public DateTime? QueueSendDate { get; set; }

    public string QueueDesc { get; set; }

    public string ReplyTo { get; set; }
}