// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.CentralModels;

public partial class PagosDetalle
{
    public int PagoDetalleId { get; set; }

    public int PagoId { get; set; }

    public string PagoDescripcion { get; set; }

    public decimal PagoPrecio { get; set; }

    public int PagoCantidad { get; set; }

    public float PagoDescuento { get; set; }

    public int? CitasPacienteId { get; set; }

    public int DescuentoId { get; set; }

    public decimal PagoPrecioOtros { get; set; }

    public string ReferenciaDet { get; set; }

    public virtual Pago Pago { get; set; }
}