// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.CentralModels;

public partial class PagosExterno
{
    public int PagoExternoId { get; set; }

    public int RefPagoId { get; set; }

    public string AreaNombre { get; set; }

    public string PagoExternoEstado { get; set; }

    public decimal PagoExternoMonto { get; set; }

    public int? PagoExternoBeneficiario { get; set; }

    public int? PagoExternoBeneficiarioDet { get; set; }

    public string CreadoPor { get; set; }

    public DateTime CreadoFecha { get; set; }

    public string ActualizadoPor { get; set; }

    public DateTime? ActualizadoFecha { get; set; }

    public string TransactionCode { get; set; }

    public string TransactionDesc { get; set; }

    public string TokenId { get; set; }

    public string TokenEmail { get; set; }

    public string TokenCardNumber { get; set; }

    public string TokenClientIp { get; set; }

    public string TokenClientBrowser { get; set; }

    public string TokenClientDeviceType { get; set; }

    public string TransactionResponse { get; set; }

    public string DocuTipo { get; set; }

    public string DocuRuc { get; set; }

    public string DocuRazonSocial { get; set; }

    public string DocuDireccion { get; set; }

    public string MonedaCodigo { get; set; }

    public string MonedaAbrev { get; set; }

    public string TokenInstallments { get; set; }

    public string TokenCardBrand { get; set; }

    public string TokenCardType { get; set; }

    public int SedeId { get; set; }

    public string DocNumero { get; set; }

    public string NombreCompleto { get; set; }

    public int? RefFacturaId { get; set; }

    public string ReferenceCode { get; set; }

    public string RefPagoTipo { get; set; }
}