// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.CentralModels;

public partial class PagoExternoVoucher
{
    public int PagoExternoVoucherId { get; set; }

    public int RefPagoId { get; set; }

    public string AreaNombre { get; set; }

    public int? PagoHc { get; set; }

    public string CreadoPor { get; set; }

    public DateTime? CreadoFecha { get; set; }

    public int SedeId { get; set; }

    public string PagoDocNumero { get; set; }

    public string NombreCompleto { get; set; }

    public int? RefFacturaId { get; set; }

    public string FileInternal { get; set; }

    public string FileExternal { get; set; }

    public string FileExtension { get; set; }

    public string PagoBanco { get; set; }

    public string PagoTipoDoc { get; set; }

    public string PagoRazonSocial { get; set; }

    public string PagoDireccion { get; set; }

    public DateTime? FechaPago { get; set; }

    public string NroOperacion { get; set; }

    public string Agencia { get; set; }

    public string PagoTipo { get; set; }

    public decimal? PagoMonto { get; set; }

    public string PagoMoneda { get; set; }

    public string PagoMonedaAbbrev { get; set; }

    public string PagoVoucherEstado { get; set; }

    public string ActualizadoPor { get; set; }

    public DateTime? ActualizadoFecha { get; set; }

    public string Email { get; set; }

    public string PagoDescripcion { get; set; }
}