// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.CentralModels;

public partial class Pago
{
    public int PagoId { get; set; }

    public int AreaId { get; set; }

    public int NumeroHistoriaClinica { get; set; }

    public int HistorialPacienteId { get; set; }

    public int EvaluacionId { get; set; }

    public int PersonalId { get; set; }

    public DateTime FechaPago { get; set; }

    public string ActualizadoPor { get; set; }

    public DateTime UltimaActualizacion { get; set; }

    public decimal OtrosPagos { get; set; }

    public string Referencia { get; set; }

    public int FacturaIdref { get; set; }

    public int SedeId { get; set; }

    public virtual ICollection<PagosDetalle> PagosDetalles { get; set; } = new List<PagosDetalle>();
}