// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.CentralModels;

public partial class Provincia
{
    public int CodigoProvincia { get; set; }

    public int CodigoDepartamento { get; set; }

    public string Nombre { get; set; }

    public virtual Departamento CodigoDepartamentoNavigation { get; set; }

    public virtual ICollection<Distrito> Distritos { get; set; } = new List<Distrito>();
}