// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.CentralModels;

public partial class UvAspnetUserRole
{
    public string Email { get; set; }

    public bool EmailConfirmed { get; set; }

    public bool TwoFactorEnabled { get; set; }

    public bool LockoutEnabled { get; set; }

    public string Rol { get; set; }

    public string Nombres { get; set; }

    public string ApellidoPaterno { get; set; }
    public string ApellidoMaterno { get; set; }
    public byte? Sexo { get; set; }
    public string TipoDoc { get; set; }
    public string Dni { get; set; }
    public int? Pais { get; set; }

    public string Telefono { get; set; }

    public DateTimeOffset? LockoutEnd { get; set; }

    public DateTime? FechaNacimiento { get; set; }

    public string UrlImagen { get; set; }

    public DateTime? CreadoFecha { get; set; }

    public string Id { get; set; }

    public int IdPerfil { get; set; }

    public string IdRol { get; set; }
}