// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.CentralModels;

public partial class UvConfiguracionVariable
{
    public string ConfigNombre { get; set; }

    public string ConfigData { get; set; }
}