// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entity.ClinicaModels;

namespace DA.ClinicaContext
{
    public partial interface ICPALClinicaContextProcedures
    {
        Task<List<upAgendaDiagnosticoV2Result>> upAgendaDiagnosticoV2Async(int? personalID, DateTime? dateFrom, DateTime? dateTo, int? sedeID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<upCalendarioDisponibleDiagV2Result>> upCalendarioDisponibleDiagV2Async(DateTime? dateInicio, int? especialidadID, int? rangoEdadID, int? personalID, int? sedeID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<upHistorialPacienteGetDiagV2Result>> upHistorialPacienteGetDiagV2Async(int? numeroHistoriaClinica, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<upHistorialPacienteGetTratV2Result>> upHistorialPacienteGetTratV2Async(int? numeroHistoriaClinica, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<upCitasProximasPorUsuarioResult>> upCitasProximasPorUsuarioAsync(string userName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<upHistoriaClinicaGetDiagnosticoV2Result>> upHistoriaClinicaGetDiagnosticoV2Async(int? numeroHistoriaClinica, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<upHistoriaClinicaGetTratamientoPUResult>> upHistoriaClinicaGetTratamientoPUAsync(int? numeroHistoriaClinica, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<upCalendarioDisponibleDiagV3PortalResult>> upCalendarioDisponibleDiagV3PortalAsync(DateTime? fechaSeleccionada, int? especialidadID, int? rangoEdadID, int? personalID, int? sedeID, int? Dias, int? tipo, int? tiempo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<upCalendarioDisponibleDiagPresencialResult>> upCalendarioDisponibleDiagPresencialAsync(int? evaluacionID, int? rangoEdadID, int? personalID, int? sedeID, int? Dias, int? tiempo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<upCalendarioDisponibleDiagVirtualResult>> upCalendarioDisponibleDiagVirtualAsync(int? evaluacionID, int? rangoEdadID, int? personalID, int? sedeID, int? Dias, int? tiempo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);

    }
}
