// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.ClinicaModels;

public partial class DetalleReservaTratamiento
{
    public int DetalleReservaTratamientoId { get; set; }

    public int? HistorialPacienteId { get; set; }

    public int ReservaTratamientoId { get; set; }

    public DateTime? DeleteDate { get; set; }

    public string DeleteBy { get; set; }

    public virtual ReservaTratamiento ReservaTratamiento { get; set; }
}