// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.ClinicaModels;

public partial class EvaluacionCitum
{
    public int EvaluacionCitaId { get; set; }

    public int? Numero { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public string Categoria { get; set; }

    public int? CategoriaNro { get; set; }

    public decimal? Precio { get; set; }

    public string ImagenUrl { get; set; }

    public string ActualizadoPor { get; set; }

    public DateTime? UltimaActualizacion { get; set; }

    public int? TipoCitaId { get; set; }

    public float? Duracion { get; set; }

    public int? EvaluacionAreaId { get; set; }

    public DateTime? EliminadoFecha { get; set; }

    public int? CitaPara { get; set; }

    public short? EvaluacionId { get; set; }

    public int? EvaluacionPublicaId { get; set; }
}