// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.ClinicaModels;

public partial class Paciente
{
    public int NumeroHistoriaClinica { get; set; }

    public int? TriageNo { get; set; }

    public DateTime FechaRegistro { get; set; }

    public string ApellidoPaterno { get; set; }

    public string ApellidoMaterno { get; set; }

    public string Nombres { get; set; }

    public DateTime FechaNacimiento { get; set; }

    public byte Sexo { get; set; }

    public string CentroEducativo { get; set; }

    public string GradoEstudios { get; set; }

    public string DerivadoPor { get; set; }

    public string MotivoConsulta { get; set; }

    public string TratamientosAnteriores { get; set; }

    public string Direccion { get; set; }

    public short? CodigoPais { get; set; }

    public int? CodigoDepartamento { get; set; }

    public int? CodigoProvincia { get; set; }

    public int? CodigoDistrito { get; set; }

    public string Telefono { get; set; }

    public string NombrePadre { get; set; }

    public string OcupacionPadre { get; set; }

    public string CentroTrabajoPadre { get; set; }

    public string TelefonoPadre { get; set; }

    public string CelularPadre { get; set; }

    public string EmailPadre { get; set; }

    public string NombreMadre { get; set; }

    public string OcupacionMadre { get; set; }

    public string CentroTrabajoMadre { get; set; }

    public string TelefonoMadre { get; set; }

    public string CelularMadre { get; set; }

    public string EmaiMadre { get; set; }

    public short? NumeroHijosVarones { get; set; }

    public short? NumeroHijosMujeres { get; set; }

    public short? LugarEntreHermanos { get; set; }

    public string FotoPaciente { get; set; }

    public string ActualizadoPor { get; set; }

    public DateTime UltimaActualizacion { get; set; }

    public string Direccion2 { get; set; }

    public string PacienteViveCon { get; set; }

    public string TelefonoEmergencia { get; set; }

    public string HistoriaNotas { get; set; }

    public string InformeIntegralDiagnostico { get; set; }

    public DateTime? FechaIngresoTratamiento { get; set; }

    public string CentroEducativoEmail { get; set; }

    public string CentroEducativoTelefono { get; set; }

    public string ProfesorNombre { get; set; }

    public string ProfesorEmail { get; set; }

    public string ProfesorTelefono { get; set; }

    public string Convenio { get; set; }

    public short? SobreDirigido { get; set; }

    public string ApoderadoNombre { get; set; }

    public short? EnviarLugar { get; set; }

    public string EnviarDireccion { get; set; }

    public short? EnviarCodigoPais { get; set; }

    public int? EnviarCodigoDepartamento { get; set; }

    public int? EnviarCodigoProvincia { get; set; }

    public int? EnviarCodigoDistrito { get; set; }

    public int? Filmar { get; set; }

    public string Obsfilmar { get; set; }

    public int? Fotografiar { get; set; }

    public string Obsfotografiar { get; set; }

    public int? Coordinarcoleg { get; set; }

    public string Obscoordinarcoleg { get; set; }

    public bool? Revista { get; set; }

    public bool? Pamarillas { get; set; }

    public bool? Prensa { get; set; }

    public string Derivado { get; set; }

    public bool? Otros { get; set; }

    public string PacienteDni { get; set; }

    public int? CodigoColegio { get; set; }

    public decimal? TratCostoTotalConDesc { get; set; }

    public decimal? TratTotalPagado { get; set; }

    public decimal? TratTotalPagadoMetodoEst { get; set; }

    public byte? Responsable { get; set; }

    public int? Clinicoacademico { get; set; }

    public string Obsclinacad { get; set; }

    public bool? Seguroescolar { get; set; }

    public bool? SeguroEssalud { get; set; }

    public bool? SeguroSis { get; set; }

    public bool? SeguroParticular { get; set; }

    public bool? SeguroOtros { get; set; }

    public string CiaSeguro1 { get; set; }

    public string CiaSeguro2 { get; set; }

    public string IndicaCasoEmergencia { get; set; }

    public DateTime? Vigencia1 { get; set; }

    public DateTime? Vigencia2 { get; set; }

    public string DniTitularSeguro { get; set; }

    public bool? Titularseguro { get; set; }

    public bool? Titularseguro2 { get; set; }

    public string DniTitularSeguro2 { get; set; }

    public DateTime? DeletedDate { get; set; }

    public int SedeId { get; set; }

    public string EmailContacto { get; set; }

    public string FotoPaciente2 { get; set; }

    public string FotoPaciente3 { get; set; }

    public string CompDatosEnviadoEstado { get; set; }

    public DateTime? CompDatosEnviadoEndDate { get; set; }

    public DateTime? CompDatosEnviadoFecha { get; set; }

    public string CompDatosEnviadoPor { get; set; }

    public string CompDatosEnviadoMailTo { get; set; }

    public DateTime? CompDatosRespuestaFecha { get; set; }

    public DateTime? FechaUltimoReingreso { get; set; }
}