// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.ClinicaModels;

public partial class PagoCita
{
    public int PagoCitaId { get; set; }

    public string UsuarioId { get; set; }

    public int? HistoriaClinica { get; set; }

    public int? TriajeOnlineId { get; set; }

    public DateTime? CreadoFecha { get; set; }

    public DateTime? EliminadoFecha { get; set; }

    public string EstadoPago { get; set; }

    public string CreadoPor { get; set; }

    public int? PagoTriajeIdRef { get; set; }

    public DateTime? TiempoDeExpiracion { get; set; }

    public virtual ICollection<PagoCitaDetalle> PagoCitaDetalles { get; set; } = new List<PagoCitaDetalle>();

    public virtual TriageOnline TriajeOnline { get; set; }
}