// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.ClinicaModels;

public partial class PagoCitaDetalle
{
    public int PagoCitaDetalleId { get; set; }

    public int? PagoCitaId { get; set; }

    public int? EvaluacionAreaId { get; set; }

    public int? EvaluacionId { get; set; }

    public int? EvaluacionCitaId { get; set; }

    public string EvaluacionNombre { get; set; }

    public string EvaluacionCitaNombre { get; set; }

    public int? NumeroCita { get; set; }

    public int? TipoCitaId { get; set; }

    public DateTime? FechaCita { get; set; }

    public float? HoraCitaDesde { get; set; }

    public float? HoraCitaHasta { get; set; }

    public decimal? Precio { get; set; }

    public int? EspecialistaId { get; set; }

    public int? SedeId { get; set; }

    public bool? IsProgramado { get; set; }

    public bool? IsPagado { get; set; }

    public virtual PagoCita PagoCita { get; set; }
}