// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.ClinicaModels;

public partial class PagosTriaje
{
    public int PagoId { get; set; }

    public string IdCargo { get; set; }

    public bool? Duplicado { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public decimal? Monto { get; set; }

    public decimal? MontoReembolsado { get; set; }

    public decimal? MontoActual { get; set; }

    public int? Cuotas { get; set; }

    public decimal? MontoCuotas { get; set; }

    public string CodigoMoneda { get; set; }

    public string CorreoElectronico { get; set; }

    public string Descripcion { get; set; }

    public int? PuntajeFraude { get; set; }

    public bool? Disputa { get; set; }

    public bool? Captura { get; set; }

    public string CodigoReferencia { get; set; }

    public string CodigoAutorizacion { get; set; }

    public decimal? TotalComision { get; set; }

    public decimal? TotalImpuestosComision { get; set; }

    public decimal? MontoTransferido { get; set; }

    public bool? Pagado { get; set; }

    public string DescriptorEstado { get; set; }

    public string IdTransferencia { get; set; }

    public DateTime? FechaCaptura { get; set; }

    public string IdToken { get; set; }

    public string Tipo { get; set; }

    public DateTime? FechaCreacionToken { get; set; }

    public string CorreoElectronicoToken { get; set; }

    public string NumeroTarjeta { get; set; }

    public string UltimosCuatro { get; set; }

    public bool? Activo { get; set; }

    public string TipoRespuesta { get; set; }

    public string CodigoRespuesta { get; set; }

    public string MensajeComercio { get; set; }

    public string MensajeUsuario { get; set; }

    public string NombreCliente { get; set; }

    public string ApellidoCliente { get; set; }

    public string DireccionCliente { get; set; }

    public string CiudadCliente { get; set; }

    public string CodigoPaisCliente { get; set; }

    public string TelefonoCliente { get; set; }

    public string DireccionIpCliente { get; set; }

    public string PaisIpCliente { get; set; }

    public string CodigoPaisIpCliente { get; set; }

    public string NavegadorCliente { get; set; }

    public string HuellaDispositivoCliente { get; set; }

    public string TipoDispositivoCliente { get; set; }

    public string Sponsor { get; set; }

    public string ClaveOrden { get; set; }

    public string IdOrden { get; set; }

    public bool? PublicarCliente { get; set; }

    public string Bin { get; set; }

    public string MarcaTarjeta { get; set; }

    public string TipoTarjeta { get; set; }

    public string CategoriaTarjeta { get; set; }

    public string CuotasPermitidas { get; set; }

    public string NombreEmisor { get; set; }

    public string PaisEmisor { get; set; }

    public string CodigoPaisEmisor { get; set; }

    public string SitioWebEmisor { get; set; }

    public string NumeroTelefonoEmisor { get; set; }

    public DateTime? FechaCreacionPedido { get; set; }

    public DateTime? FechaPagoPedido { get; set; }

    public string EstadoPedido { get; set; }

    public string ViaCreacionPedido { get; set; }

    public string CartHash { get; set; }

    public string SimboloMonedaPedido { get; set; }

    public string Productos { get; set; }

    public string Sede { get; set; }

    public string DniCliente { get; set; }

    public string TipoBoletaFactura { get; set; }

    public string RucClienteFacturacion { get; set; }

    public string NombreClienteFacturacion { get; set; }

    public int? Estado { get; set; }

    public string ActualizadoPor { get; set; }

    public DateTime? UltimaActualizacion { get; set; }

    public bool? Atencion { get; set; }

    public string NroTriaje { get; set; }

    public string NroHc { get; set; }

    public int? PagoCitaIdRef { get; set; }

    public string CitasDetalle { get; set; }

    public string TipoDocCliente { get; set; }
}