// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.ClinicaModels;

public partial class PersonalHorario
{
    public int PersonalHorarioId { get; set; }

    public int PersonalId { get; set; }

    public DateTime PeriodoInicio { get; set; }

    public DateTime? PeriodoFin { get; set; }

    public DateTime? LunesInicio { get; set; }

    public DateTime? LunesFin { get; set; }

    public DateTime? MartesInicio { get; set; }

    public DateTime? MartesFin { get; set; }

    public DateTime? MiercolesInicio { get; set; }

    public DateTime? MiercolesFin { get; set; }

    public DateTime? JuevesInicio { get; set; }

    public DateTime? JuevesFin { get; set; }

    public DateTime? ViernesInicio { get; set; }

    public DateTime? ViernesFin { get; set; }

    public DateTime? SabadoInicio { get; set; }

    public DateTime? SabadoFin { get; set; }

    public DateTime? DomingoInicio { get; set; }

    public DateTime? DomingoFin { get; set; }

    public DateTime? LunesInicioTarde { get; set; }

    public DateTime? LunesFinTarde { get; set; }

    public DateTime? MartesInicioTarde { get; set; }

    public DateTime? MartesFinTarde { get; set; }

    public DateTime? MiercolesInicioTarde { get; set; }

    public DateTime? MiercolesFinTarde { get; set; }

    public DateTime? JuevesInicioTarde { get; set; }

    public DateTime? JuevesFinTarde { get; set; }

    public DateTime? ViernesInicioTarde { get; set; }

    public DateTime? ViernesFinTarde { get; set; }

    public DateTime? SabadoInicioTarde { get; set; }

    public DateTime? SabadoFinTarde { get; set; }

    public DateTime? DomingoInicioTarde { get; set; }

    public DateTime? DomingoFinTarde { get; set; }

    public DateTime? LunesInicioTra { get; set; }

    public DateTime? LunesFinTra { get; set; }

    public DateTime? MartesInicioTra { get; set; }

    public DateTime? MartesFinTra { get; set; }

    public DateTime? MiercolesInicioTra { get; set; }

    public DateTime? MiercolesFinTra { get; set; }

    public DateTime? JuevesInicioTra { get; set; }

    public DateTime? JuevesFinTra { get; set; }

    public DateTime? ViernesInicioTra { get; set; }

    public DateTime? ViernesFinTra { get; set; }

    public DateTime? SabadoInicioTra { get; set; }

    public DateTime? SabadoFinTra { get; set; }

    public DateTime? DomingoInicioTra { get; set; }

    public DateTime? DomingoFinTra { get; set; }

    public DateTime? LunesInicioTardeTra { get; set; }

    public DateTime? LunesFinTardeTra { get; set; }

    public DateTime? MartesInicioTardeTra { get; set; }

    public DateTime? MartesFinTardeTra { get; set; }

    public DateTime? MiercolesInicioTardeTra { get; set; }

    public DateTime? MiercolesFinTardeTra { get; set; }

    public DateTime? JuevesInicioTardeTra { get; set; }

    public DateTime? JuevesFinTardeTra { get; set; }

    public DateTime? ViernesInicioTardeTra { get; set; }

    public DateTime? ViernesFinTardeTra { get; set; }

    public DateTime? SabadoInicioTardeTra { get; set; }

    public DateTime? SabadoFinTardeTra { get; set; }

    public DateTime? DomingoInicioTardeTra { get; set; }

    public DateTime? DomingoFinTardeTra { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string LastUpdatedBy { get; set; }

    public int SedeId { get; set; }

    public DateTime? LunesInicioVirDiag { get; set; }

    public DateTime? LunesFinVirDiag { get; set; }

    public DateTime? MartesInicioVirDiag { get; set; }

    public DateTime? MartesFinVirDiag { get; set; }

    public DateTime? MiercolesInicioVirDiag { get; set; }

    public DateTime? MiercolesFinVirDiag { get; set; }

    public DateTime? JuevesInicioVirDiag { get; set; }

    public DateTime? JuevesFinVirDiag { get; set; }

    public DateTime? ViernesInicioVirDiag { get; set; }

    public DateTime? ViernesFinVirDiag { get; set; }

    public DateTime? SabadoInicioVirDiag { get; set; }

    public DateTime? SabadoFinVirDiag { get; set; }

    public DateTime? DomingoInicioVirDiag { get; set; }

    public DateTime? DomingoFinVirDiag { get; set; }

    public DateTime? LunesInicioVirTra { get; set; }

    public DateTime? LunesFinVirTra { get; set; }

    public DateTime? MartesInicioVirTra { get; set; }

    public DateTime? MartesFinVirTra { get; set; }

    public DateTime? MiercolesInicioVirTra { get; set; }

    public DateTime? MiercolesFinVirTra { get; set; }

    public DateTime? JuevesInicioVirTra { get; set; }

    public DateTime? JuevesFinVirTra { get; set; }

    public DateTime? ViernesInicioVirTra { get; set; }

    public DateTime? ViernesFinVirTra { get; set; }

    public DateTime? SabadoInicioVirTra { get; set; }

    public DateTime? SabadoFinVirTra { get; set; }

    public DateTime? DomingoInicioVirTra { get; set; }

    public DateTime? DomingoFinVirTra { get; set; }

    public DateTime? LunesInicioVirDiagTarde { get; set; }

    public DateTime? LunesFinVirDiagTarde { get; set; }

    public DateTime? MartesInicioVirDiagTarde { get; set; }

    public DateTime? MartesFinVirDiagTarde { get; set; }

    public DateTime? MiercolesInicioVirDiagTarde { get; set; }

    public DateTime? MiercolesFinVirDiagTarde { get; set; }

    public DateTime? JuevesInicioVirDiagTarde { get; set; }

    public DateTime? JuevesFinVirDiagTarde { get; set; }

    public DateTime? ViernesInicioVirDiagTarde { get; set; }

    public DateTime? ViernesFinVirDiagTarde { get; set; }

    public DateTime? SabadoInicioVirDiagTarde { get; set; }

    public DateTime? SabadoFinVirDiagTarde { get; set; }

    public DateTime? DomingoInicioVirDiagTarde { get; set; }

    public DateTime? DomingoFinVirDiagTarde { get; set; }

    public DateTime? LunesInicioVirTraTarde { get; set; }

    public DateTime? LunesFinVirTraTarde { get; set; }

    public DateTime? MartesInicioVirTraTarde { get; set; }

    public DateTime? MartesFinVirTraTarde { get; set; }

    public DateTime? MiercolesInicioVirTraTarde { get; set; }

    public DateTime? MiercolesFinVirTraTarde { get; set; }

    public DateTime? JuevesInicioVirTraTarde { get; set; }

    public DateTime? JuevesFinVirTraTarde { get; set; }

    public DateTime? ViernesInicioVirTraTarde { get; set; }

    public DateTime? ViernesFinVirTraTarde { get; set; }

    public DateTime? SabadoInicioVirTraTarde { get; set; }

    public DateTime? SabadoFinVirTraTarde { get; set; }

    public DateTime? DomingoInicioVirTraTarde { get; set; }

    public DateTime? DomingoFinVirTraTarde { get; set; }
}