// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.ClinicaModels;
public partial class ReservaTratamiento
{
    public int ReservaTratamientoId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? DeleteDate { get; set; }

    public string DeleteBy { get; set; }

    public int ReservaTratamientoEstadoId { get; set; }

    public string EmailRegistro { get; set; }

    public int? PersonalId { get; set; }

    public string ActualizadoPor { get; set; }

    public DateTime? UltimaActualizacion { get; set; }

    public int SedeId { get; set; }

    public int? RefNroHistoriaClinica { get; set; }

    public string RefUsuarioId { get; set; }

    public string OrientacionMedio { get; set; }

    public string Observaciones { get; set; }

    public int? Tipo { get; set; }

    public virtual ICollection<DetalleReservaTratamiento> DetalleReservaTratamientos { get; set; } = new List<DetalleReservaTratamiento>();

}