// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.ClinicaModels;

public partial class TriageCotejo
{
    public int TriageCotejoId { get; set; }

    public int TriageOnlineId { get; set; }

    public bool? RespondeLlamado { get; set; }

    public string RespondeLlamadoObs { get; set; }

    public bool? ContactVisual { get; set; }

    public string ContactVisualObs { get; set; }

    public bool? SonrieRespuesta { get; set; }

    public string SonrieRespuestaOnb { get; set; }

    public bool? MuestraObjetos { get; set; }

    public string MuestraObjetosObs { get; set; }

    public bool? DirigeMiradaObjeto { get; set; }

    public string DirigeMiradaObjetoObs { get; set; }

    public bool? JuegaConPersonas { get; set; }

    public string JuegaConPersonasObd { get; set; }

    public bool? SeDejaEntender { get; set; }

    public string SeDejaEntenderObs { get; set; }

    public bool? LlamaAtencion { get; set; }

    public string LlamaAtencionObs { get; set; }

    public bool? PedirAlgoInteres { get; set; }

    public string PedirAlgoInteresObs { get; set; }

    public bool? PalabrasEmite { get; set; }

    public string PalabrasEmiteObs { get; set; }

    public bool? UtilizaLenguaje { get; set; }

    public string UtilizaLenguajeObs { get; set; }

    public bool? RepiteDice { get; set; }

    public string RepiteDiceObs { get; set; }

    public bool? RepiteFrases { get; set; }

    public string RepiteFrasesObs { get; set; }

    public bool? HablaTerceraPersona { get; set; }

    public string HablaTerceraPersonaObs { get; set; }

    public bool? CogeObjetos { get; set; }

    public string CogeObjetosObs { get; set; }

    public bool? BrindaFuncionObjeto { get; set; }

    public string BrindaFuncionObjetoObs { get; set; }

    public bool? PuedeJuegoDos { get; set; }

    public string PuedeJuegoDosObs { get; set; }

    public bool? RealizarMoviRepetido { get; set; }

    public string RealizarMoviRepetidoObs { get; set; }

    public bool? InteresInusual { get; set; }

    public string InteresInusualObs { get; set; }

    public bool? LlevaObjetosBoca { get; set; }

    public string LlevaObjetosBocaObs { get; set; }

    public bool? MolestanRuidos { get; set; }

    public string MolestanRuidosObs { get; set; }

    public bool? DisgustaTocar { get; set; }

    public string DisgustaTocarObs { get; set; }

    public bool? RehusaComer { get; set; }

    public string RehusaComerObs { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string ActualizadoPor { get; set; }

    public DateTime? ActualizadoFecha { get; set; }

    public string CotejoEstado { get; set; }

    public string EnviadoPor { get; set; }

    public DateTime? EnviadoFecha { get; set; }

    public string RespuestaPor { get; set; }

    public DateTime? RespuestaFecha { get; set; }

    public virtual TriageOnline TriageOnline { get; set; }
}