// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Entity.ClinicaModels;

public partial class TriageCotejoExt
{
    public int TriageCotejoExtId { get; set; }

    public int TriageOnlineId { get; set; }

    public bool? Lenguaje01 { get; set; }

    public bool? Lenguaje02 { get; set; }

    public bool? Lenguaje03 { get; set; }

    public bool? Lenguaje04 { get; set; }

    public bool? Lenguaje05 { get; set; }

    public bool? Lenguaje06 { get; set; }

    public bool? Lenguaje07 { get; set; }

    public bool? Lenguaje08 { get; set; }

    public bool? Lenguaje09 { get; set; }

    public bool? Lenguaje10 { get; set; }

    public bool? Lenguaje11 { get; set; }

    public bool? Lenguaje12 { get; set; }

    public bool? Lenguaje13 { get; set; }

    public bool? Habla01 { get; set; }

    public bool? Habla02 { get; set; }

    public bool? Habla03 { get; set; }

    public bool? Habla04 { get; set; }

    public bool? Habla05 { get; set; }

    public bool? Habla06 { get; set; }

    public bool? Habla07 { get; set; }

    public bool? Habla08 { get; set; }

    public bool? Habla09 { get; set; }

    public bool? Habla10 { get; set; }

    public bool? Habla11 { get; set; }

    public bool? Habla12 { get; set; }

    public bool? Habla13 { get; set; }

    public bool? Habla14 { get; set; }

    public bool? Habla15 { get; set; }

    public bool? Habla16 { get; set; }

    public bool? Habla17 { get; set; }

    public bool? Habla18 { get; set; }

    public bool? Aprend01 { get; set; }

    public bool? Aprend02 { get; set; }

    public bool? Aprend03 { get; set; }

    public bool? Aprend04 { get; set; }

    public bool? Aprend05 { get; set; }

    public bool? Aprend06 { get; set; }

    public bool? Aprend07 { get; set; }

    public bool? Aprend08 { get; set; }

    public bool? Aprend09 { get; set; }

    public bool? Aprend10 { get; set; }

    public bool? Aprend11 { get; set; }

    public bool? Aprend12 { get; set; }

    public bool? Aprend13 { get; set; }

    public bool? Cuerpo01 { get; set; }

    public bool? Cuerpo02 { get; set; }

    public bool? Cuerpo03 { get; set; }

    public bool? Cuerpo04 { get; set; }

    public bool? Cuerpo05 { get; set; }

    public bool? Cuerpo06 { get; set; }

    public bool? Cuerpo07 { get; set; }

    public bool? Cuerpo08 { get; set; }

    public bool? Cuerpo09 { get; set; }

    public bool? Cuerpo10 { get; set; }

    public bool? Cuerpo11 { get; set; }

    public bool? Cuerpo12 { get; set; }

    public bool? Cuerpo13 { get; set; }

    public bool? Cuerpo14 { get; set; }

    public bool? UdadPl01 { get; set; }

    public bool? UdadPl02 { get; set; }

    public bool? UdadPl03 { get; set; }

    public bool? UdadPl04 { get; set; }

    public bool? UdadPl05 { get; set; }

    public bool? UdadPl06 { get; set; }

    public bool? UdadPl07 { get; set; }

    public bool? UdadJuego01 { get; set; }

    public bool? UdadJuego02 { get; set; }

    public bool? UdadEstereo01 { get; set; }

    public bool? UdadEstereo02 { get; set; }

    public bool? UdadSensorial01 { get; set; }

    public bool? UdadSensorial02 { get; set; }

    public bool? UdadSensorial03 { get; set; }

    public bool? UdadSensorial04 { get; set; }

    public bool? UdadLf01 { get; set; }

    public bool? UdadLf02 { get; set; }

    public bool? UdadLf03 { get; set; }

    public bool? UdadLf04 { get; set; }

    public bool? UdadLf05 { get; set; }

    public bool? UdadLf06 { get; set; }

    public bool? UdadConduc01 { get; set; }

    public bool? UdadConduc02 { get; set; }

    public bool? UdadConduc03 { get; set; }

    public bool? UdadConduc04 { get; set; }

    public bool? UdadFsenso01 { get; set; }

    public bool? UdadFsenso02 { get; set; }

    public bool? AudioProcAud01 { get; set; }

    public bool? AudioProcAud02 { get; set; }

    public bool? AudioProcAud03 { get; set; }

    public bool? AudioProcAud04 { get; set; }

    public bool? AudioProcAud05 { get; set; }

    public bool? AudioProcAud06 { get; set; }

    public bool? AudioProcAud07 { get; set; }

    public bool? AudioProcAud08 { get; set; }

    public bool? AudioProcAud09 { get; set; }

    public bool? AudioProcAud10 { get; set; }

    public bool? AudioPerdBebe01 { get; set; }

    public bool? AudioPerdBebe02 { get; set; }

    public bool? AudioPerdBebe03 { get; set; }

    public bool? AudioPerdBebe04 { get; set; }

    public bool? AudioPerdBebe05 { get; set; }

    public bool? AudioPerdBebe06 { get; set; }

    public bool? AudioPerdBebe07 { get; set; }

    public bool? AudioPerdBebe08 { get; set; }

    public bool? AudioPerdBebe09 { get; set; }

    public bool? AudioPerdBebe10 { get; set; }

    public bool? AudioPerdAdul01 { get; set; }

    public bool? AudioPerdAdul02 { get; set; }

    public bool? AudioPerdAdul03 { get; set; }

    public bool? AudioPerdAdul04 { get; set; }

    public bool? AudioPerdAdul05 { get; set; }

    public bool? AudioPerdAdul06 { get; set; }

    public bool? AudioPerdAdul07 { get; set; }

    public bool? AudioPerdAdul08 { get; set; }

    public bool? AudioPerdAdul09 { get; set; }

    public bool? AudioPerdAdul10 { get; set; }

    public string Psicologia01 { get; set; }

    public bool? AprendPre01 { get; set; }

    public bool? AprendPre02 { get; set; }

    public bool? AprendPre03 { get; set; }

    public bool? AprendPre04 { get; set; }

    public bool? AprendPre05 { get; set; }

    public bool? AprendPre06 { get; set; }

    public bool? AprendPre07 { get; set; }

    public bool? AprendPre08 { get; set; }

    public bool? AprendPre09 { get; set; }

    public bool? AprendPre10 { get; set; }

    public bool? AprendEsc01 { get; set; }

    public bool? AprendEsc02 { get; set; }

    public bool? AprendEsc03 { get; set; }

    public bool? AprendEsc04 { get; set; }

    public bool? AprendEsc05 { get; set; }

    public bool? AprendEsc06 { get; set; }

    public bool? AprendEsc07 { get; set; }

    public bool? AprendEsc08 { get; set; }

    public bool? AprendEsc09 { get; set; }

    public bool? AprendEsc10 { get; set; }

    public bool? AprendEsc11 { get; set; }

    public bool? AprendEsc12 { get; set; }

    public bool? AprendEsc13 { get; set; }

    public bool? AprendEsc14 { get; set; }

    public bool? AprendEsc15 { get; set; }

    public bool? AprendUni01 { get; set; }

    public bool? AprendUni02 { get; set; }

    public bool? AprendUni03 { get; set; }

    public bool? AprendUni04 { get; set; }

    public bool? AprendUni05 { get; set; }

    public bool? AprendUni06 { get; set; }

    public bool? AprendUni07 { get; set; }

    public bool? AprendUni08 { get; set; }

    public bool? AprendAdul01 { get; set; }

    public bool? AprendAdul02 { get; set; }

    public bool? AprendAdul03 { get; set; }

    public bool? AprendAdul04 { get; set; }

    public bool? AprendAdul05 { get; set; }

    public bool? AprendAdul06 { get; set; }

    public string LenguajeObs { get; set; }

    public string HablaObs { get; set; }

    public string AprendiObs { get; set; }

    public string CuerpoObs { get; set; }

    public string UdadObs { get; set; }

    public string AudioObs { get; set; }

    public string PsicoObs { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string ActualizadoPor { get; set; }

    public DateTime? ActualizadoFecha { get; set; }

    public virtual TriageOnline TriageOnline { get; set; }
}