// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entity.ClinicaModels
{
    public partial class upAgendaDiagnosticoV2Result
    {
        public string citaID { get; set; }
        public int citasPacienteID { get; set; }
        public int numeroHistoriaClinica { get; set; }
        public int areaID { get; set; }
        public DateTime? fechaCita { get; set; }
        public float horaCitaDesde { get; set; }
        public float horaCitaHasta { get; set; }
        public DateTime? fechaCitaDesde { get; set; }
        public DateTime? fechaCitaHasta { get; set; }
        public int personalID { get; set; }
        public string apellidos { get; set; }
        public string evaluacionAbreviacion { get; set; }
        public int numeroCita { get; set; }
        public int estadoCitaID { get; set; }
        public int? grupoID { get; set; }
        public int? parentGrupoID { get; set; }
        public int asistioCita { get; set; }
        public string notasCita { get; set; }
        public string citaColor { get; set; }
        public string descripcion { get; set; }
        public string parentGrupo { get; set; }
        public int historialEstadoID { get; set; }
        public string creadoPor { get; set; }
        public int? edad { get; set; }
        public int ultimaCita { get; set; }
        public string apellidoPaterno { get; set; }
    }
}
