// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entity.ClinicaModels
{
    public partial class upCalendarioDisponibleDiagV3PortalResult
    {
        public int DiaIndex { get; set; }
        public int DiaSemana { get; set; }
        public string NombreDiaSemana { get; set; }
        public DateTime Fecha { get; set; }

        public DateTime Hora8Inicio { get; set; }
        public DateTime Hora8Fin { get; set; }
        public string Hora8List { get; set; }

        public DateTime Hora9Inicio { get; set; }
        public DateTime Hora9Fin { get; set; }
        public string Hora9List { get; set; }

        public DateTime Hora10Inicio { get; set; }
        public DateTime Hora10Fin { get; set; }
        public string Hora10List { get; set; }

        public DateTime Hora11Inicio { get; set; }
        public DateTime Hora11Fin { get; set; }
        public string Hora11List { get; set; }

        public DateTime Hora12Inicio { get; set; }
        public DateTime Hora12Fin { get; set; }
        public string Hora12List { get; set; }

        public DateTime Hora13Inicio { get; set; }
        public DateTime Hora13Fin { get; set; }
        public string Hora13List { get; set; }

        public DateTime Hora14Inicio { get; set; }
        public DateTime Hora14Fin { get; set; }
        public string Hora14List { get; set; }

        public DateTime Hora15Inicio { get; set; }
        public DateTime Hora15Fin { get; set; }
        public string Hora15List { get; set; }

        public DateTime Hora16Inicio { get; set; }
        public DateTime Hora16Fin { get; set; }
        public string Hora16List { get; set; }

        public DateTime Hora17Inicio { get; set; }
        public DateTime Hora17Fin { get; set; }
        public string Hora17List { get; set; }

        public DateTime Hora18Inicio { get; set; }
        public DateTime Hora18Fin { get; set; }
        public string Hora18List { get; set; }

        public DateTime Hora19Inicio { get; set; }
        public DateTime Hora19Fin { get; set; }
        public string Hora19List { get; set; }

        public DateTime Hora20Inicio { get; set; }
        public DateTime Hora20Fin { get; set; }
        public string Hora20List { get; set; }
    }
}
