// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entity.ClinicaModels
{
    public partial class upCalendarioDisponibleDiagV2Result
    {
        public int HorarioDiagnosticoID { get; set; }
        public float HoraInicio { get; set; }
        public float HoraFin { get; set; }
        public DateTime HoraInicial { get; set; }
        public DateTime HoraFinal { get; set; }
        public DateTime day1 { get; set; }
        public DateTime day2 { get; set; }
        public DateTime day3 { get; set; }
        public DateTime day4 { get; set; }
        public DateTime day5 { get; set; }
        public DateTime day6 { get; set; }
        public DateTime day7 { get; set; }
        public string day1List { get; set; }
        public string day2List { get; set; }
        public string day3List { get; set; }
        public string day4List { get; set; }
        public string day5List { get; set; }
        public string day6List { get; set; }
        public string day7List { get; set; }

    }
}
