// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entity.ClinicaModels
{
    public partial class upCitasProximasPorUsuarioResult
    {
        public string emailPadre { get; set; }
        public string emaiMadre { get; set; }
        public int numeroHistoriaClinica { get; set; }
        public int numeroCita { get; set; }
        public string Tipo { get; set; }
        public DateTime? fechaCita { get; set; }
        public float horaCitaDesde { get; set; }
        public float horaCitaHasta { get; set; }
        public string nombre_paciente { get; set; }
        public string evaluacion { get; set; }
        public string Area { get; set; }
        public string Sede { get; set; }
        public string emailcontacto { get; set; }
    }
}
