// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entity.ClinicaModels
{
    public partial class upHistorialPacienteGetDiagV2Result
    {
        public int historialPacienteID { get; set; }
        public int esCitaPago { get; set; }
        public int numeroHistoriaClinica { get; set; }
        public int numeroRegistro { get; set; }
        public int? pagoID { get; set; }
        public string evaluacionNombre { get; set; }
        public string fullName { get; set; }
        public int? personalID { get; set; }
        public DateTime? fechaInicio { get; set; }
        public DateTime? fechaFin { get; set; }
        public short? historialEstadoID { get; set; }
        public string nombreEstado { get; set; }
        public short? finalizarTipoID { get; set; }
        public string finalizarNombreAbbre { get; set; }
        public DateTime? FechaPago { get; set; }
        public int? countCitas { get; set; }
        public double? costoTotal { get; set; }
        public string pagoFacturaNro { get; set; }
        public string facturaEstadoNombre { get; set; }
        public short? evaluacionID { get; set; }
        public int? descuentoID { get; set; }
        public float? descuento { get; set; }
        public int evaluacionGrupal { get; set; }
        public string actualizadoPor { get; set; }
        public DateTime? ultimaActualizacion { get; set; }
        public decimal otrosPagos { get; set; }
        public string pagoActualizadoPor { get; set; }
        public DateTime? pagoUltimaActualizacion { get; set; }
        public bool prueba { get; set; }
        public string sedeNameEval { get; set; }
        public int sedeIDHP { get; set; }
        public string personalApellidos { get; set; }
        public int? facturaID { get; set; }
        public string pagoDescripcion { get; set; }
        public string pagoExternoEstado { get; set; }
        public DateTime? creadoFecha { get; set; }
        public string docuTipo { get; set; }
        public string pagoExternoVoucherEstado { get; set; }
        public DateTime? creadoFechaPagoVoucher { get; set; }
        public string docuTipoPagoVoucher { get; set; }
        public int? totalPagosSinFactura { get; set; }
    }
}
