// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entity.ClinicaModels
{
    public partial class upHistoriaClinicaGetDiagnosticoV2Result
    {
        public int historialPacienteID { get; set; }
        public int esCitaPago { get; set; }
        public int numeroHistoriaClinica { get; set; }
        public int numeroRegistro { get; set; }
        public int? citasPacienteID { get; set; }
        public DateTime? fechaCita { get; set; }
        public int? pagoID { get; set; }
        public string evaluacionNombre { get; set; }
        public string fullName { get; set; }
        public int? personalID { get; set; }
        public DateTime? fechaInicio { get; set; }
        public DateTime? fechaFin { get; set; }
        public short? historialEstadoID { get; set; }
        public string nombreEstado { get; set; }
        public string informeBorrador { get; set; }
        public string informeRevisado { get; set; }
        public string planFileInterno { get; set; }
        public short? finalizarTipoID { get; set; }
        public string finalizarNombreAbbre { get; set; }
        public int? numeroCita { get; set; }
        public float? horaCitaDesde { get; set; }
        public float? horaCitaHasta { get; set; }
        public bool? asistioCita { get; set; }
        public int? estadoCitaID { get; set; }
        public string citaEstadoNombre { get; set; }
        public bool? interconsulta { get; set; }
        public string numeroFactura { get; set; }
        public DateTime? FechaPago { get; set; }
        public int? countCitas { get; set; }
        public double? costoTotal { get; set; }
        public string pagoFacturaNro { get; set; }
        public string facturaEstadoNombre { get; set; }
        public int lastHistorialPacienteID { get; set; }
        public int evaluacionConFrecuencia { get; set; }
        public int? facturaID { get; set; }
        public short? evaluacionID { get; set; }
        public int? descuentoID { get; set; }
        public float? descuento { get; set; }
        public int evaluacionGrupal { get; set; }
        public float lunesHoraDesde { get; set; }
        public float lunesHoraHasta { get; set; }
        public float martesHoraDesde { get; set; }
        public float martesHoraHasta { get; set; }
        public float miercolesHoraDesde { get; set; }
        public float miercolesHoraHasta { get; set; }
        public float juevesHoraDesde { get; set; }
        public float juevesHoraHasta { get; set; }
        public float viernesHoraDesde { get; set; }
        public float viernesHoraHasta { get; set; }
        public float sabadoHoraDesde { get; set; }
        public float sabadoHoraHasta { get; set; }
        public float domingoHoraDesde { get; set; }
        public float domingoHoraHasta { get; set; }
        public string actualizadoPor { get; set; }
        public DateTime? ultimaActualizacion { get; set; }
        public DateTime? reservadaDesde { get; set; }
        public DateTime? reservadaHasta { get; set; }
        public int? citaGratuita { get; set; }
        public int? conclusion { get; set; }
        public int? ultimaCita { get; set; }
        public string numeroRecibo { get; set; }
        public bool? citaTelefono { get; set; }
        public string notasCita { get; set; }
        public string observaciones { get; set; }
        public string creadoPor { get; set; }
        public DateTime? fechaCreacion { get; set; }
        public string citaActualizadoPor { get; set; }
        public DateTime? citaUltimaActualizacion { get; set; }
        public short? CitaPara { get; set; }
        public int? pagoDetalleID { get; set; }
        public decimal otrosPagos { get; set; }
        public string pagoActualizadoPor { get; set; }
        public DateTime? pagoUltimaActualizacion { get; set; }
        public bool prueba { get; set; }
        public string consultorioNombre { get; set; }
        public string sedeNameCita { get; set; }
        public string sedeNameEval { get; set; }
        public int sedeIDHP { get; set; }
        public int pagoExternoID { get; set; }
        public int? citaTipoID { get; set; }
    }
}
