// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.ClinicaModels;

public partial class UvEspecilidadesPublica
{
    public string Especialidad { get; set; }

    public int? EspecialidadId { get; set; }

    public int? AreaId { get; set; }

    public string Area { get; set; }

    public string EspecialidadVariable { get; set; }

    public string EspecialidadDescripcion { get; set; }

    public string EspecialidadPublica { get; set; }

    public int? EspecialidadNroOrden { get; set; }
}