// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.ClinicaModels;

public partial class UvEvaluacionesPublica
{
    public int EvaluacionPublicaId { get; set; }

    public string EspecialidadPublica { get; set; }

    public string Variable { get; set; }

    public int? EvaluacionPublicaNroOrden { get; set; }

    public int? EvaluacionPublicaIdpadre { get; set; }

    public string EvaluacionPublica { get; set; }

    public int? Sesiones { get; set; }

    public short? EvaluacionId { get; set; }

    public string Evaluacion { get; set; }

    public string DescripcionEvaluacion { get; set; }

    public string Especialidad { get; set; }

    public int EspecialidadId { get; set; }

    public string DescripcionEspecialidad { get; set; }

    public int? AreaId { get; set; }

    public string Area { get; set; }
}