// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.ClinicaModels;

public partial class UvHistoriaDiagnosticoBusqueda2
{
    public int NumeroHistoriaClinica { get; set; }

    public int HistorialPacienteId { get; set; }

    public string Evaluacion { get; set; }

    public string TerapiaAsociada { get; set; }

    public string Especialista { get; set; }

    public DateTime FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public DateTime? InformeBorradorProgramada { get; set; }

    public DateTime? InformeBorradorEntrega { get; set; }

    public DateTime? InformeRevisadoProgramada { get; set; }

    public DateTime? InformeRevisadoEntrega { get; set; }

    public string InformeBorrador { get; set; }

    public string InformeRevisado { get; set; }

    public string InformeIndividual { get; set; }

    public int? PersonalId { get; set; }

    public string NombreEstado { get; set; }

    public short Tipo { get; set; }

    public int NumeroRegistro { get; set; }

    public short HistorialEstadoId { get; set; }

    public string InfBorradorCorregir1 { get; set; }

    public DateTime? InfBorradorCorregir1Fecha { get; set; }

    public string InfBorradorCorregir1Entrega { get; set; }

    public DateTime? InfBorradorCorregir1EntregaFecha { get; set; }

    public string InfBorradorCorregir2 { get; set; }

    public DateTime? InfBorradorCorregir2Fecha { get; set; }

    public string InfBorradorCorregir2Entrega { get; set; }

    public DateTime? InfBorradorCorregir2EntregaFecha { get; set; }

    public DateTime? InfRevisadoEntregaRecepcion { get; set; }

    public short FinalizarTipoId { get; set; }

    public string FinalizarNombre { get; set; }

    public DateTime? Revaluar { get; set; }
}