// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.ClinicaModels;

public partial class UvPagoCitasSearch
{
    public int PagoCitaId { get; set; }

    public string UsuarioId { get; set; }

    public int? HistoriaClinica { get; set; }

    public int? TriajeOnlineId { get; set; }

    public DateTime? CreadoFecha { get; set; }

    public DateTime? EliminadoFecha { get; set; }

    public string EstadoPago { get; set; }

    public string CreadoPor { get; set; }

    public int PagoCitaDetalleId { get; set; }

    public int? EvaluacionAreaId { get; set; }

    public int? EvaluacionId { get; set; }

    public int? EvaluacionCitaId { get; set; }

    public string Nombre { get; set; }

    public string CitaNombre { get; set; }

    public int? TipoCitaId { get; set; }

    public DateTime? FechaCita { get; set; }

    public float? HoraCitaDesde { get; set; }

    public float? HoraCitaHasta { get; set; }

    public int? NumeroCita { get; set; }

    public decimal? Precio { get; set; }

    public int? EspecialistaId { get; set; }

    public int? SedeId { get; set; }

    public string Sede { get; set; }

    public DateTime? FechaNacimientoPaciente { get; set; }

    public int? Edad { get; set; }

    public string ImagenUrl { get; set; }
}