// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.ClinicaModels;

public partial class UvPersonalEvaluacionSearch
{
    public short EvaluacionId { get; set; }

    public int PersonalPorcentageId { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public float Porcentage { get; set; }

    public float? Monto { get; set; }

    public bool? PorcentajeTipo { get; set; }

    public int PersonalId { get; set; }

    public int? RangoEdadAtencionId { get; set; }
}