// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.ClinicaModels;


public partial class UvReservaTratamientoSearch
{
    public int ReservaTratamientoId { get; set; }

    public string ApellidoPaterno { get; set; }

    public string ApellidoMaterno { get; set; }

    public string Nombres { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? DeleteDate { get; set; }

    public string Estado { get; set; }

    public string EmailRegistro { get; set; }

    public int? PersonalId { get; set; }

    public string Sede { get; set; }

    public int? HistoriaClinica { get; set; }

    public string UsuarioId { get; set; }

    public string OrientacionMedio { get; set; }

    public string Terapia { get; set; }

    public int ReservaTratamientoEstadoId { get; set; }

    public int? Tipo { get; set; }

    public string Observaciones { get; set; }
}