// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entity.CentralModels;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;

namespace DA.CentralContext
{
    public partial class CPALCentralContext
    {
        private ICPALCentralContextProcedures _procedures;

        public virtual ICPALCentralContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new CPALCentralContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ICPALCentralContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class CPALCentralContextProcedures : ICPALCentralContextProcedures
    {
        private readonly CPALCentralContext _context;

        public CPALCentralContextProcedures(CPALCentralContext context)
        {
            _context = context;
        }

        public virtual async Task upV2UpdatePagoDetalleReferenciaAsync(int pagoID, string referenciaDet, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            string query = "EXEC upV2UpdatePagoDetalleReferencia " + pagoID.ToString() + ",'" + referenciaDet + "'";
            await _context.Database.ExecuteSqlRawAsync(query);
        }
    }
}
