// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entity.ClinicaModels;

namespace DA.CentralContext
{
    public partial interface ICPALCentralContextProcedures
    {
        Task upV2UpdatePagoDetalleReferenciaAsync(int pagoID, string referenciaDet, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
